{
 "title": "Docker Engine Native Metrics",
 "description": "Draw some docker metrics",
 "tags": [
  "docker",
  "docker metrics",
  "docker engine"
 ],
 "time": { "from": "2018-10-15T12:28:56.673Z", "to": "2018-10-15T12:29:05.368Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "instance", "label": "Instance", "query": "engine_daemon_engine_info" }
  ]
 },
 "panels": [
  {
   "title": "Docker Info",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "engine_daemon_engine_info",
     "legendFormat": "<p>docker version: {{version}}<p>os: {{os}}<p>kernel: {{kernel}}<p>graphdriver: {{graphdriver}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Number of CPUs",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "engine_daemon_engine_cpus_cpus{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes"
    }
   ]
  },
  {
   "title": "Container States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Number of failed image builds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "builder_builds_failed_total", "legendFormat": "{{reason}}" }
   ]
  },
  {
   "title": "Number of triggered image builds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "builder_builds_triggered_total" }
   ]
  },
  {
   "title": "Total Container Actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_count{instance=~'$instance'}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Total Network Actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_network_actions_seconds_count{instance=~'$instance'}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "etcd fsync wall percentile",
   "type": "graph",
   "description": "Measuring histogram on some percentile",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "50"
    },
    {
     "expr": "histogram_quantile(0.10, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "10"
    }
   ]
  },
  {
   "title": "Event Subscribers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_events_subscribers_total{instance=~'$instance'}",
     "legendFormat": " "
    }
   ]
  }
 ]
}